export const keywordColors = [
  { name: "health", value: "#1F995C" },
  { name: "hp", value: "#1F995C" },
  { name: "haste", value: "#FFFDC9" },
  { name: "ah", value: "#FFFDC9" },
  { name: "radiant", value: "#EABE3F" },
  { name: "attack damage", value: "orange" },
  { name: "attack's damage", value: "orange" },
  { name: "ad", value: "orange" },
  { name: "physical damage", value: "#FF8C34" },
  { name: "pd", value: "#FF8C34" },
  { name: "ability power", value: "#7A6DFF" },
  { name: "ap", value: "#7A6DFF" },
  { name: "magic damage", value: "#00B0F0" },
  { name: "md", value: "#00B0F0" },
  { name: "true damage", value: "#F9966B" },
  { name: "td", value: "#F9966B" },
  { name: "armor", value: "yellow" },
  { name: "armor penetration", value: "tomato" },
  { name: "lethality", value: "tomato" },
  { name: "omnivamp", value: "#CC2051" },
  { name: "leech", value: "#CC2051" },
  { name: "life steal", value: "#CC2051" },
  { name: "ls", value: "#CC2051" },
  { name: "magic resist", value: "#00FFFF" },
  { name: "mr", value: "#00FFFF" },
  { name: "resist", value: "#00FFFF" },
  { name: "magic penetration", value: "turquoise" },
  { name: "mana", value: "#0099CC" },
  { name: "energy", value: "yellow" },
  { name: "critical strike chance", value: "orangered" },
  { name: "critical chance", value: "orangered" },
  { name: "critical strike damage", value: "orangered" },
  { name: "critical damage", value: "#944B00" },
  { name: "crit", value: "#944B00" },
  { name: "movement speed", value: "#F5EE99" },
  { name: "move speed", value: "#F5EE99" },
  { name: "ms", value: "#F5EE99" },
  { name: "xp", value: "#883FD1" },
  { name: "gold", value: "#FFD700" },
  { name: "siphoning strike", value: "#594BDD" },
  { name: "soul", value: "#5C58C9" },
  { name: "buzzword4", value: "#BB76AC" },
  { name: "buzzword3", value: "#E34D4C" },
  { name: "buzzword2", value: "#56C456" },
  { name: "buzzword", value: "#AF1AAF" },
  { name: "mist", value: "#26DFB0" },
  { name: "wild", value: "#A01D7A" },
  { name: "placed", value: "#883FD1" },
  { name: "attack speed", value: "orangered" },
  { name: "as", value: "orangered" },
  { name: "fury", value: "#FA6533" },
  { name: "river", value: "#43D9FB" },
  { name: "terrain", value: "#B36F21" },
  { name: "brush", value: "#96FB97" },
  { name: "life point", value: "#56C456" },
  { name: "main", value: "#CA2697" },
  { name: "off%-hand", value: "#E34D4C" },
  { name: "sweetspot", value: "#E34D4C" },
  { name: "exalted", value: "#FF7F00" },
  { name: "steel", value: "#748DD0" },
  { name: "azakana", value: "#E34D4C" },
  { name: "stardust", value: "#4262F0" },
  { name: "overcharge", value: "deeppink" },
  { name: "heal", value: "#60E08F" },
  { name: "range", value: "#FFFDC9" },
  { name: "ar", value: "yellow" },
];

export interface TooltipData {
  name: string;
  alias?: string;
  type: string;
  icon?: string;
}

export const tooltipData = [
  {
    name: "Acquisition radius",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/1/1e/Acquisition_range.png",
  },
  {
    name: "Adaptive damage",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/0/07/Attack_damage.png",
  },
  {
    name: "Adaptive force",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/b/bd/Adaptive_Force_icon.png",
  },
  {
    name: "Attached",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/b/b2/Yuumi_You_and_Me%21.png",
  },
  {
    name: "Bandit",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/7/70/Bandit_mastery_2016.png",
  },
  {
    name: "Basic attack",
    type: "General",
  },
  {
    name: "Basic attack reset",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/f/f4/Fiora_Bladework.png",
  },
  {
    name: "Blink",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/7/74/Flash.png",
  },
  {
    name: "Block",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/0/0a/Shen_Spirit%27s_Refuge.png",
  },
  {
    name: "Brittle",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/c/c3/Brittle_icon.png",
  },
  {
    name: "Cc-immune",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/b/b1/Cc-immune_icon.png",
  },
  {
    name: "Centered range",
    alias: "cr",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/c/cf/Range_center.png",
  },
  {
    name: "Champion",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/2/25/Champion_icon.png",
  },
  {
    name: "Channel",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/b/bb/Channeling_icon.png",
  },
  {
    name: "Cleanse",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/3/3e/Gangplank_Remove_Scurvy.png",
  },
  {
    name: "Complete crowd control",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/5/5f/Suppression_icon.png",
  },
  {
    name: "Critical strike",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/4/41/Critical_strike_icon.png",
  },
  {
    name: "Crowd control",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/9/9d/Stun_icon.png",
  },
  {
    name: "Dash",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/5/55/Dash.png",
  },
  {
    name: "Death",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/c/c3/Death.png",
  },
  {
    name: "Disarming crowd control",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/e/ed/Disarm_icon.png",
  },
  {
    name: "Dispel",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/7/79/Anivia_Rebirth.png",
  },
  {
    name: "Dodge",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/6/62/Jax_Counter_Strike_old.png",
  },
  {
    name: "Drain",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/2/24/Ravenous_Hunter_rune.png",
  },
  {
    name: "Edge range",
    alias: "er",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/7/71/Range_model.png",
  },
  {
    name: "Energized",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/d/d1/Kircheis_Shard_item.png",
  },
  {
    name: "Energy",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/e/ea/Energy_resource.png",
  },
  {
    name: "Execute",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/1/19/Pyke_Death_from_Below.png",
  },
  {
    name: "Forced action",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/e/ea/Forced_action_icons.png",
  },
  {
    name: "Fury",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/d/d7/Fury_resource.png",
  },
  {
    name: "Gameplay radius",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/4/48/Gameplay_radius.png",
  },
  {
    name: "Ghosted",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/a/ab/Ghost.png",
  },
  {
    name: "Grievous wounds",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/b/bf/Grievous_Wounds_icon.png",
  },
  {
    name: "Health resource",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/1/15/Health_resource.png",
  },
  {
    name: "Immobilize",
    alias: "Impaired",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/9/9d/Stun_icon.png",
  },
  {
    name: "Interrupt",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/4/49/Silence_icon.png",
  },
  {
    name: "Invulnerability",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/4/49/Taric_Cosmic_Radiance.png",
  },
  {
    name: "Lockout",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/7/72/Lockout_icon_2.png",
  },
  {
    name: "Lunge",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/e/ec/Udyr_Bear_Stance.png",
  },
  {
    name: "Manaless",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/c/cd/Manaless_resource.png",
  },
  {
    name: "Mutilator",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/2/26/Mutilator.png",
  },
  {
    name: "Omnivamp",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/a/a7/Omnivamp_colored_icon.png",
  },
  {
    name: "Pathing radius",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/7/7b/Pathing_radius.png",
  },
  {
    name: "Poison",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/8/84/Poison_icon.png",
  },
  {
    name: "Projectile",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/6/6b/Projectile.png",
  },
  {
    name: "Resurrection",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/7/7c/Revival_icon.png",
  },
  {
    name: "Selection radius",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/4/4a/Selection_radius.png",
  },
  {
    name: "Spell shield",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/a/a0/Sivir_Spell_Shield.png",
  },
  {
    name: "Stasis",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/e/e2/Stasis_icon.png",
  },
  {
    name: "Takedown",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/0/07/Damage_rating.png",
  },
  {
    name: "Tenacity",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/3/33/Tenacity_icon.png",
  },
  {
    name: "Displacement immunity",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/4/42/Unstoppable_icon.png",
  },
  {
    name: "Uncancellable windup",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/5/5b/Vi_Relentless_Force_2.png",
  },
  {
    name: "Untargetable",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/4/41/Untargetable_icon.png",
  },
  {
    name: "Vanish",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/6/65/Shaco_Hallucinate.png",
  },
  {
    name: "Dragon locked",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/0/06/Locked_Dragon_buff.png",
  },
  {
    name: "Zombie state",
    type: "General",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/b/b9/Zombie_icon.png",
  },
  {
    name: "Brush",
    alias: "Bush",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/e/ef/Ivern_Brushmaker.png",
  },
  {
    name: "Sight",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/0/0e/Sight_icon.png",
  },
  {
    name: "Unobstructed vision",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/b/b5/Stealth_Ward_icon.png",
  },
  {
    name: "True sight",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/1/18/True_Sight_icon.png",
  },
  {
    name: "Exposed",
    alias: "Expose",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/2/2b/Exposed_icon.png",
  },
  {
    name: "Disabled ward",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/c/c3/Disabled_Ward_icon.png",
  },
  {
    name: "Control ward",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/9/95/Control_Ward_icon.png",
  },
  {
    name: "Farsight ward",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/2/29/Farsight_Ward_icon.png",
  },
  {
    name: "Siege ward",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/4/46/Totem_Ward_icon.png",
  },
  {
    name: "Stealth ward",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/b/b5/Stealth_Ward_icon.png",
  },
  {
    name: "Sweeper drone",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/d/db/Sweeper_Drone_icon.png",
  },
  {
    name: "Totem ward",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/4/46/Totem_Ward_icon.png",
  },
  {
    name: "Zombie ward",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/2/29/Farsight_Ward_icon.png",
  },
  {
    name: "Ghost poro",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/4/46/Totem_Ward_icon.png",
  },
  {
    name: "Ward rubble",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/6/69/Ward_Rubble_icon.png",
  },
  {
    name: "Stealth",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/3/3a/Teemo_Guerrilla_Warfare.png",
  },
  {
    name: "Camouflage",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/3/32/Twitch_Ambush_2.png",
  },
  {
    name: "Invisibility",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/3/34/Akali_Twilight_Shroud_old2.png",
  },
  {
    name: "Obscured vision",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/d/db/Sweeper_Drone_icon.png",
  },
  {
    name: "Stealthed trap",
    type: "Vision and Wards",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/5/5e/Teemo_Noxious_Trap.png",
  },
  {
    name: "Unit-targeted",
    type: "Targeting paradigms",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/c/ca/Jax_Leap_Strike.png",
  },
  {
    name: "Direction-targeted",
    type: "Targeting paradigms",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/4/43/Brand_Sear.png",
  },
  {
    name: "Ground-targeted",
    type: "Targeting paradigms",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/c/c3/Xerath_Eye_of_Destruction.png",
  },
  {
    name: "Auto-targeted",
    type: "Targeting paradigms",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/2/20/Kennen_Electrical_Surge.png",
  },
  {
    name: "Aura",
    type: "Targeting paradigms",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/8/8d/Sona_Aria_of_Perseverance.png",
  },
  {
    name: "Krugs",
    type: "Jungle & Minions",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/f/fe/Ancient_KrugSquare.png",
  },
  {
    name: "Murk wolves",
    type: "Jungle & Minions",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/d/d6/Greater_Murk_WolfSquare.png",
  },
  {
    name: "Raptors",
    alias: "chickens",
    type: "Jungle & Minions",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/9/94/Crimson_RaptorSquare.png",
  },
  {
    name: "Golems",
    type: "Jungle & Minions",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/f/fb/Ancient_Golem_Icon_profileicon.jpg/revision/latest/scale-to-width-down/20?cb=20221125202548png",
  },
  {
    name: "Wraiths",
    type: "Jungle & Minions",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/4/44/Wraith_Icon_profileicon.jpg/revision/latest/scale-to-width-down/20?cb=20221125215430png",
  },
  {
    name: "Wolves",
    type: "Jungle & Minions",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/c/c6/Level_Two_Critter_Icon_profileicon.jpg/revision/latest/scale-to-width-down/20?cb=20221125215315png",
  },
  {
    name: "Impatience",
    type: "Jungle & Minions",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/d/de/Frenzy_mastery_2013.png",
  },
  {
    name: "Minion",
    type: "Jungle & Minions",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/3/30/Minion_icon.png",
  },
  {
    name: "Monster",
    type: "Jungle & Minions",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/d/d1/Monster_icon.png",
  },
  {
    name: "Pet",
    type: "Pets and other unit types",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/9/92/Annie_Summon-_Tibbers.png",
  },
  {
    name: "Clone",
    type: "Pets and other unit types",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/d/d7/Shaco_Command-_Hallucinate.png",
  },
  {
    name: "Effigy",
    type: "Pets and other unit types",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/4/46/Totem_Ward_icon.png",
  },
  {
    name: "Turret",
    type: "Turret",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png",
  },
  {
    name: "Nexus obelisk",
    type: "Turret",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/d/d2/Nexus_Obelisk.png",
  },
  {
    name: "Penetrating bullets",
    type: "Turret",
    icon: "https://static.wikia.nocookie.net/leagueoflegends/images/7/7c/Penetrating_Bullets.png",
  },
];
