# This is a basic workflow that is manually triggered

name: Build custom DDragon JSON files

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: "0 5 * * 3"
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  itemsBuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    name: Build Items
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies with a clean slate
        run: npm install
      - name: Build dist
        run: npm run build
      - name: Build custom json files
        # id: items
        # uses: OchreFox/league-custom-ddragon@main
        run: npm run start
      - name: Run tests
        run: npm run test
      - name: Commit files only when the branch is main
        id: commit
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          git commit -m "Auto-generated new files" -a || echo "Nothing to update"
          echo "push=true" >> $GITHUB_OUTPUT
        shell: bash
      - name: Push changes to master
        if: steps.commit.outputs.push == 'true' && github.ref == 'refs/heads/main'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
